repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^deploy/podman/kube-spec\.yaml$
      - id: check-yaml
        files: ^deploy/podman/kube-spec\.yaml$
        args: ['--allow-multiple-documents']
      - id: check-added-large-files
