package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	repoProviderPath = "deploy/grafana/provisioning/dashboards/dashboards.yaml"
	repoDashboardDir = "deploy/grafana/dashboards"
	generatorID      = "deploy/podman/cmd/generate-grafana-configmaps"
)

func main() {
	var output string
	flag.StringVar(&output, "o", "", "write output here instead of stdout")
	flag.StringVar(&output, "output", "", "write output here instead of stdout")
	flag.Parse()

	out, err := renderGrafanaConfigMaps()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if output == "" {
		fmt.Print(out)
		return
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o700); err != nil {
		fmt.Fprintf(os.Stderr, "error: mkdir output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(output, []byte(out), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "error: write %s: %v\n", output, err)
		os.Exit(1)
	}
}

func renderGrafanaConfigMaps() (string, error) {
	root, err := repoRoot()
	if err != nil {
		return "", err
	}

	providerPath := filepath.Join(root, filepath.FromSlash(repoProviderPath))
	provider, err := os.ReadFile(providerPath)
	if err != nil {
		return "", fmt.Errorf("missing file %s: %w", repoProviderPath, err)
	}

	dashboardPaths, err := filepath.Glob(filepath.Join(root, filepath.FromSlash(repoDashboardDir), "*.json"))
	if err != nil {
		return "", err
	}

	sort.Strings(dashboardPaths)
	if len(dashboardPaths) == 0 {
		return "", fmt.Errorf("no *.json dashboards under %s", repoDashboardDir)
	}

	dashboards := make(map[string]string, len(dashboardPaths))
	dashboardRelPaths := make([]string, 0, len(dashboardPaths))
	for _, path := range dashboardPaths {
		b, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return "", err
		}
		dashboardRelPaths = append(dashboardRelPaths, filepath.ToSlash(rel))
		dashboards[filepath.Base(path)] = string(b)
	}

	var out bytes.Buffer
	out.WriteString(grafanaBanner(dashboardRelPaths))
	out.WriteString("\n---\n")
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	for _, doc := range []*yaml.Node{
		grafanaConfigMapNode("vectis-grafana-dashboard-provider", map[string]string{"dashboards.yaml": string(provider)}),
		grafanaConfigMapNode("vectis-grafana-dashboards", dashboards),
	} {
		if err := enc.Encode(doc); err != nil {
			_ = enc.Close()
			return "", fmt.Errorf("encode grafana configmap: %w", err)
		}
	}
	if err := enc.Close(); err != nil {
		return "", fmt.Errorf("close yaml encoder: %w", err)
	}

	return out.String(), nil
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(repoProviderPath))); err == nil {
				return dir, nil
			}
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root from %s", dir)
		}
		dir = parent
	}
}

func grafanaBanner(dashboardPaths []string) string {
	sources := append([]string{repoProviderPath}, dashboardPaths...)
	return strings.Join([]string{
		fmt.Sprintf("# Generated by %s - DO NOT EDIT.", generatorID),
		"# Sources: " + strings.Join(sources, ", "),
		fmt.Sprintf("# Regenerate: go run ./%s -o deploy/podman/grafana-configmaps.gen.yaml", generatorID),
	}, "\n")
}

type yamlPair struct {
	key   string
	value *yaml.Node
}

func grafanaConfigMapNode(name string, data map[string]string) *yaml.Node {
	return mappingNode(
		pair("apiVersion", scalarNode("v1")),
		pair("kind", scalarNode("ConfigMap")),
		pair("metadata", mappingNode(
			pair("name", scalarNode(name)),
			pair("annotations", mappingNode(
				pair("vectis.grafana/generator", scalarNode(generatorID)),
			)),
		)),
		pair("data", literalDataNode(data)),
	)
}

func literalDataNode(data map[string]string) *yaml.Node {
	keys := make([]string, 0, len(data))
	for key := range data {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	n := &yaml.Node{Kind: yaml.MappingNode}
	for _, key := range keys {
		n.Content = append(n.Content, scalarNode(key), literalNode(data[key]))
	}
	return n
}

func mappingNode(pairs ...yamlPair) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode}
	for _, p := range pairs {
		n.Content = append(n.Content, scalarNode(p.key), p.value)
	}
	return n
}

func pair(key string, value *yaml.Node) yamlPair {
	return yamlPair{key: key, value: value}
}

func scalarNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value}
}

func literalNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: strings.TrimRight(value, "\n") + "\n", Style: yaml.LiteralStyle}
}
