package gerrit

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	sdkscm "vectis/sdk/scm"
)

const (
	DefaultReviewRevision = "current"
	DefaultReviewTag      = "autogenerated:vectis"
	MaxErrorBytes         = 4096
)

type Client struct {
	BaseURL    string
	Username   string
	Password   string
	HTTPClient *http.Client
}

type ReviewRequest struct {
	Change    string
	Revision  string
	Message   string
	Label     string
	LabelVote int
	Tag       string
}

func (c Client) ChangeDetail(ctx context.Context, change string) (sdkscm.Change, error) {
	endpoint, err := c.endpoint("/a/changes/" + url.PathEscape(strings.TrimSpace(change)) + "/detail?o=CURRENT_REVISION")
	if err != nil {
		return sdkscm.Change{}, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return sdkscm.Change{}, err
	}

	c.setAuth(req)
	resp, err := c.httpClient().Do(req)
	if err != nil {
		return sdkscm.Change{}, fmt.Errorf("get Gerrit change detail: %w", err)
	}
	defer resp.Body.Close()

	var info sdkscm.Change
	if err := DecodeJSON(resp, &info); err != nil {
		return sdkscm.Change{}, fmt.Errorf("get Gerrit change detail: %w", err)
	}

	return info, nil
}

func (c Client) QueryChanges(ctx context.Context, query sdkscm.Query) ([]sdkscm.Change, error) {
	rawQuery := gerritChangeQuery(query)
	if rawQuery == "" {
		return nil, fmt.Errorf("Gerrit change query is required")
	}

	values := url.Values{}
	values.Set("q", rawQuery)
	values.Add("o", "CURRENT_REVISION")

	endpoint, err := c.endpoint("/a/changes/?" + values.Encode())
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, err
	}

	c.setAuth(req)
	resp, err := c.httpClient().Do(req)
	if err != nil {
		return nil, fmt.Errorf("query Gerrit changes: %w", err)
	}
	defer resp.Body.Close()

	var changes []sdkscm.Change
	if err := DecodeJSON(resp, &changes); err != nil {
		return nil, fmt.Errorf("query Gerrit changes: %w", err)
	}

	return changes, nil
}

func (c Client) PostReview(ctx context.Context, req ReviewRequest) error {
	req.Revision = strings.TrimSpace(req.Revision)
	if req.Revision == "" {
		req.Revision = DefaultReviewRevision
	}

	endpoint, err := c.endpoint("/a/changes/" + url.PathEscape(strings.TrimSpace(req.Change)) + "/revisions/" + url.PathEscape(req.Revision) + "/review")
	if err != nil {
		return err
	}

	payload, err := reviewPayload(req)
	if err != nil {
		return err
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal Gerrit review input: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("create Gerrit review request: %w", err)
	}

	httpReq.Header.Set("Accept", "application/json")
	httpReq.Header.Set("Content-Type", "application/json; charset=UTF-8")
	c.setAuth(httpReq)

	resp, err := c.httpClient().Do(httpReq)
	if err != nil {
		return fmt.Errorf("post Gerrit review: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		message := strings.TrimSpace(ReadErrorBody(resp.Body))
		if message == "" {
			message = resp.Status
		}

		return fmt.Errorf("Gerrit review failed with status %s: %s", resp.Status, message)
	}

	if strings.TrimSpace(req.Label) == "" {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}

	bodyText, err := readReviewBody(resp.Body)
	if err != nil {
		return err
	}

	return verifyReviewLabel(bodyText, req.Label, req.LabelVote)
}

func gerritChangeQuery(q sdkscm.Query) string {
	parts := []string{}
	if project := strings.TrimSpace(q.Project); project != "" {
		parts = append(parts, "project:"+project)
	}

	if branch := strings.TrimSpace(q.Branch); branch != "" {
		parts = append(parts, "branch:"+branch)
	}

	if status := strings.TrimSpace(q.Status); status != "" {
		parts = append(parts, "status:"+status)
	}

	if changeID := strings.TrimSpace(q.ChangeID); changeID != "" {
		parts = append(parts, "change:"+changeID)
	}

	return strings.Join(parts, " ")
}

func ParseLabelValue(raw string) (int, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return 0, fmt.Errorf("Gerrit review label value is required")
	}

	vote, err := strconv.Atoi(value)
	if err != nil {
		return 0, fmt.Errorf("Gerrit review label value must be an integer: %w", err)
	}

	return vote, nil
}

func IsHTTPURL(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil {
		return false
	}

	return u.Scheme == "http" || u.Scheme == "https"
}

func DecodeJSON(resp *http.Response, out any) error {
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("status=%d body=%s", resp.StatusCode, ReadErrorBody(resp.Body))
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	data = StripXSSIPrefix(data)
	if err := json.Unmarshal(data, out); err != nil {
		return fmt.Errorf("decode Gerrit JSON: %w", err)
	}

	return nil
}

func ReadErrorBody(body io.Reader) string {
	b, err := io.ReadAll(io.LimitReader(body, MaxErrorBytes))
	if err != nil {
		return ""
	}

	return string(StripXSSIPrefix(b))
}

func StripXSSIPrefix(b []byte) []byte {
	return bytes.TrimPrefix(b, []byte(")]}'\n"))
}

func (c Client) endpoint(path string) (string, error) {
	u, err := url.Parse(strings.TrimSpace(c.BaseURL))
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("Gerrit URL must be absolute")
	}

	if u.Scheme != "http" && u.Scheme != "https" {
		return "", fmt.Errorf("Gerrit URL must use http or https")
	}

	prefix := u.Scheme + "://" + u.Host
	if basePath := strings.TrimRight(u.EscapedPath(), "/"); basePath != "" {
		prefix += basePath
	}

	return prefix + path, nil
}

func (c Client) setAuth(req *http.Request) {
	if strings.TrimSpace(c.Username) == "" && strings.TrimSpace(c.Password) == "" {
		return
	}

	req.SetBasicAuth(c.Username, c.Password)
}

func (c Client) httpClient() *http.Client {
	if c.HTTPClient != nil {
		return c.HTTPClient
	}

	return &http.Client{Timeout: 30 * time.Second}
}

func reviewPayload(req ReviewRequest) (map[string]any, error) {
	message := req.Message
	if strings.TrimSpace(message) == "" {
		return nil, fmt.Errorf("Gerrit review message is required")
	}

	payload := map[string]any{
		"message": message,
	}

	tag := strings.TrimSpace(req.Tag)
	if tag == "" {
		tag = DefaultReviewTag
	}

	if tag != "" {
		payload["tag"] = tag
	}

	label := strings.TrimSpace(req.Label)
	if label != "" {
		payload["labels"] = map[string]int{label: req.LabelVote}
	}

	return payload, nil
}

func readReviewBody(body io.Reader) (string, error) {
	b, err := io.ReadAll(body)
	if err != nil {
		return "", fmt.Errorf("read Gerrit review response: %w", err)
	}

	return string(StripXSSIPrefix(b)), nil
}

func verifyReviewLabel(body, label string, want int) error {
	body = strings.TrimSpace(body)
	if body == "" {
		return fmt.Errorf("Gerrit review response did not confirm label %q", label)
	}

	var result struct {
		Labels map[string]int `json:"labels"`
	}

	if err := json.Unmarshal([]byte(body), &result); err != nil {
		return fmt.Errorf("decode Gerrit review response: %w", err)
	}

	got, ok := result.Labels[label]
	if !ok {
		return fmt.Errorf("Gerrit review response did not confirm label %q", label)
	}

	if got != want {
		return fmt.Errorf("Gerrit review response label %q = %d, want %d", label, got, want)
	}

	return nil
}
