package builtins

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	api "vectis/api/gen/go"
	"vectis/internal/action"
)

const (
	gerritReviewDefaultRevision = "current"
	gerritReviewDefaultTag      = "autogenerated:vectis"
	gerritReviewMaxErrorBytes   = 4096
)

type GerritReviewAction struct {
	client *http.Client
}

func NewGerritReviewAction(client *http.Client) *GerritReviewAction {
	return &GerritReviewAction{client: client}
}

func (g *GerritReviewAction) Type() string {
	return "builtins/gerrit-review"
}

func (g *GerritReviewAction) InputSchema() []action.FieldSpec {
	return []action.FieldSpec{
		{Name: "url", Type: action.FieldURL, Required: true},
		{Name: "change", Type: action.FieldString, Required: true},
		{Name: "revision", Type: action.FieldString},
		{Name: "message", Type: action.FieldString, Required: true},
		{Name: "label", Type: action.FieldString},
		{Name: "value", Type: action.FieldString},
		{Name: "tag", Type: action.FieldString},
		{Name: "username", Type: action.FieldString, Required: true},
		{Name: "password_file", Type: action.FieldString, Required: true},
	}
}

func (g *GerritReviewAction) ValidateWith(with map[string]string) []action.FieldError {
	errs := action.ValidateWithSpec(with, g.InputSchema())

	if hasCredentialedCloneURL(with["url"]) {
		errs = append(errs, action.FieldError{Field: "url", Message: "must not include embedded credentials"})
	}

	if with["url"] != "" && !isHTTPURL(with["url"]) {
		errs = append(errs, action.FieldError{Field: "url", Message: "must use http or https"})
	}

	label := strings.TrimSpace(with["label"])
	value := strings.TrimSpace(with["value"])
	switch {
	case label == "" && value != "":
		errs = append(errs, action.FieldError{Field: "value", Message: "requires label"})
	case label != "" && value == "":
		errs = append(errs, action.FieldError{Field: "value", Message: "is required when label is set"})
	case label != "":
		if _, err := parseGerritLabelValue(value); err != nil {
			errs = append(errs, action.FieldError{Field: "value", Message: "must be an integer label vote"})
		}
	}

	for _, field := range []string{"change", "revision", "label", "tag", "username", "password_file"} {
		if containsLineBreak(with[field]) {
			errs = append(errs, action.FieldError{Field: field, Message: "must be a single line"})
		}
	}

	return errs
}

func (g *GerritReviewAction) Execute(ctx context.Context, state *action.ExecutionState, inputs map[string]any, _ action.Ports) action.Result {
	req, err := gerritReviewRequestFromInputs(state, inputs)
	if err != nil {
		return action.NewFailureResult(err)
	}

	endpoint, err := gerritReviewEndpoint(req.BaseURL, req.Change, req.Revision)
	if err != nil {
		return action.NewFailureResult(err)
	}

	body, err := json.Marshal(req.Payload)
	if err != nil {
		return action.NewFailureResult(fmt.Errorf("marshal Gerrit review input: %w", err))
	}

	displayURL := redactCloneURL(req.BaseURL)
	state.Logger.Info("Posting Gerrit review: %s change=%s revision=%s", displayURL, req.Change, req.Revision)
	sendLog(state, api.Stream_STREAM_STDOUT, fmt.Sprintf("Posting Gerrit review for change %s revision %s", req.Change, req.Revision))

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return action.NewFailureResult(fmt.Errorf("create Gerrit review request: %w", err))
	}

	httpReq.Header.Set("Accept", "application/json")
	httpReq.Header.Set("Content-Type", "application/json; charset=UTF-8")
	httpReq.SetBasicAuth(req.Username, req.Password)

	resp, err := g.httpClient().Do(httpReq)
	if err != nil {
		return action.NewFailureResult(fmt.Errorf("post Gerrit review: %w", err))
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		message := strings.TrimSpace(readGerritErrorBody(resp.Body))
		if message == "" {
			message = resp.Status
		}

		return action.NewFailureResult(fmt.Errorf("Gerrit review failed with status %s: %s", resp.Status, message))
	}

	if req.Label != "" {
		body, err := readGerritReviewBody(resp.Body)
		if err != nil {
			return action.NewFailureResult(err)
		}

		if err := verifyGerritReviewLabel(body, req.Label, req.LabelVote); err != nil {
			return action.NewFailureResult(err)
		}
	} else {
		_, _ = io.Copy(io.Discard, resp.Body)
	}

	sendLog(state, api.Stream_STREAM_STDOUT, "Gerrit review posted successfully")
	return action.NewSuccessResult(map[string]any{
		"change":   req.Change,
		"revision": req.Revision,
		"reviewed": true,
	})
}

func (g *GerritReviewAction) httpClient() *http.Client {
	if g.client != nil {
		return g.client
	}

	return &http.Client{Timeout: 30 * time.Second}
}

type gerritReviewRequest struct {
	BaseURL   string
	Change    string
	Revision  string
	Username  string
	Password  string
	Label     string
	LabelVote int
	Payload   map[string]any
}

func gerritReviewRequestFromInputs(state *action.ExecutionState, inputs map[string]any) (gerritReviewRequest, error) {
	baseURL, err := requiredStringInput(inputs, "url")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	if hasCredentialedCloneURL(baseURL) {
		return gerritReviewRequest{}, fmt.Errorf("Gerrit URL must not include embedded credentials")
	}

	change, err := requiredSingleLineInput(inputs, "change")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	revision, err := optionalSingleLineInput(inputs, "revision", gerritReviewDefaultRevision)
	if err != nil {
		return gerritReviewRequest{}, err
	}

	message, err := requiredStringInput(inputs, "message")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	username, err := requiredSingleLineInput(inputs, "username")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	passwordFile, err := requiredSingleLineInput(inputs, "password_file")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	password, err := readGerritPasswordFile(state, passwordFile)
	if err != nil {
		return gerritReviewRequest{}, err
	}

	tag, err := optionalSingleLineInput(inputs, "tag", gerritReviewDefaultTag)
	if err != nil {
		return gerritReviewRequest{}, err
	}

	payload := map[string]any{
		"message": message,
	}

	if tag != "" {
		payload["tag"] = tag
	}

	label, err := optionalSingleLineInput(inputs, "label", "")
	if err != nil {
		return gerritReviewRequest{}, err
	}

	value, hasValue := inputs["value"]
	if label != "" {
		rawValue, ok := value.(string)
		if !ok || strings.TrimSpace(rawValue) == "" {
			return gerritReviewRequest{}, fmt.Errorf("Gerrit review value is required when label is set")
		}

		vote, err := parseGerritLabelValue(rawValue)
		if err != nil {
			return gerritReviewRequest{}, err
		}

		label = strings.TrimSpace(label)
		payload["labels"] = map[string]int{label: vote}
		return gerritReviewRequest{
			BaseURL:   baseURL,
			Change:    change,
			Revision:  revision,
			Username:  username,
			Password:  password,
			Label:     label,
			LabelVote: vote,
			Payload:   payload,
		}, nil
	} else if hasValue {
		rawValue, ok := value.(string)
		if !ok || strings.TrimSpace(rawValue) != "" {
			return gerritReviewRequest{}, fmt.Errorf("Gerrit review value requires label")
		}
	}

	return gerritReviewRequest{
		BaseURL:  baseURL,
		Change:   change,
		Revision: revision,
		Username: username,
		Password: password,
		Payload:  payload,
	}, nil
}

func gerritReviewEndpoint(baseURL, change, revision string) (string, error) {
	u, err := url.Parse(baseURL)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("Gerrit URL must be absolute")
	}

	if u.Scheme != "http" && u.Scheme != "https" {
		return "", fmt.Errorf("Gerrit URL must use http or https")
	}

	prefix := u.Scheme + "://" + u.Host
	if path := strings.TrimRight(u.EscapedPath(), "/"); path != "" {
		prefix += path
	}

	return prefix + "/a/changes/" + url.PathEscape(change) + "/revisions/" + url.PathEscape(revision) + "/review", nil
}

func readGerritPasswordFile(state *action.ExecutionState, rawPath string) (string, error) {
	workspace := ""
	if state != nil {
		workspace = state.Workspace
	}

	path, err := workspaceRelativePath(workspace, rawPath)
	if err != nil {
		return "", fmt.Errorf("Gerrit password_file: %w", err)
	}

	b, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read Gerrit password_file: %w", err)
	}

	password := strings.TrimRight(string(b), "\r\n")
	if password == "" {
		return "", fmt.Errorf("Gerrit password_file must not be empty")
	}

	return password, nil
}

func readGerritErrorBody(body io.Reader) string {
	b, err := io.ReadAll(io.LimitReader(body, gerritReviewMaxErrorBytes))
	if err != nil {
		return ""
	}

	return string(stripGerritXSSIPrefix(b))
}

func readGerritReviewBody(body io.Reader) (string, error) {
	b, err := io.ReadAll(body)
	if err != nil {
		return "", fmt.Errorf("read Gerrit review response: %w", err)
	}

	return string(stripGerritXSSIPrefix(b)), nil
}

func verifyGerritReviewLabel(body, label string, want int) error {
	body = strings.TrimSpace(body)
	if body == "" {
		return fmt.Errorf("Gerrit review response did not confirm label %q", label)
	}

	var result struct {
		Labels map[string]int `json:"labels"`
	}

	if err := json.Unmarshal([]byte(body), &result); err != nil {
		return fmt.Errorf("decode Gerrit review response: %w", err)
	}

	got, ok := result.Labels[label]
	if !ok {
		return fmt.Errorf("Gerrit review response did not confirm label %q", label)
	}

	if got != want {
		return fmt.Errorf("Gerrit review response label %q = %d, want %d", label, got, want)
	}

	return nil
}

func stripGerritXSSIPrefix(b []byte) []byte {
	return bytes.TrimPrefix(b, []byte(")]}'\n"))
}

func requiredStringInput(inputs map[string]any, name string) (string, error) {
	raw, ok := inputs[name]
	if !ok {
		return "", fmt.Errorf("Gerrit review requires %q input", name)
	}

	value, ok := raw.(string)
	if !ok || strings.TrimSpace(value) == "" {
		return "", fmt.Errorf("Gerrit review requires %q input", name)
	}

	return value, nil
}

func requiredSingleLineInput(inputs map[string]any, name string) (string, error) {
	value, err := requiredStringInput(inputs, name)
	if err != nil {
		return "", err
	}

	value = strings.TrimSpace(value)
	if containsLineBreak(value) {
		return "", fmt.Errorf("Gerrit review %q must be a single line", name)
	}

	return value, nil
}

func optionalSingleLineInput(inputs map[string]any, name, fallback string) (string, error) {
	raw, ok := inputs[name]
	if !ok {
		return fallback, nil
	}

	value, ok := raw.(string)
	if !ok {
		return "", fmt.Errorf("Gerrit review %q must be a string", name)
	}

	value = strings.TrimSpace(value)
	if value == "" {
		return fallback, nil
	}

	if containsLineBreak(value) {
		return "", fmt.Errorf("Gerrit review %q must be a single line", name)
	}

	return value, nil
}

func parseGerritLabelValue(raw string) (int, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return 0, fmt.Errorf("Gerrit review label value is required")
	}

	vote, err := strconv.Atoi(value)
	if err != nil {
		return 0, fmt.Errorf("Gerrit review label value must be an integer: %w", err)
	}

	return vote, nil
}

func containsLineBreak(value string) bool {
	return strings.ContainsAny(value, "\x00\r\n")
}

func isHTTPURL(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil {
		return false
	}

	return u.Scheme == "http" || u.Scheme == "https"
}
