#!/usr/bin/env python3
"""Build Kubernetes ConfigMaps for Grafana from deploy/grafana/ (see Makefile: grafana-kube-configmaps).

Uses the dashboard file provider at deploy/grafana/provisioning/dashboards/dashboards.yaml and every
*.json file under deploy/grafana/dashboards/.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PROVIDER_SRC = REPO_ROOT / "deploy/grafana/provisioning/dashboards/dashboards.yaml"
DASHBOARD_DIR = REPO_ROOT / "deploy/grafana/dashboards"

GENERATOR_ANNOTATION = "deploy/podman/generate-grafana-configmaps.py"


def _dashboard_json_paths() -> list[Path]:
    return sorted(DASHBOARD_DIR.glob("*.json"))


def _rel_to_repo(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def _literal_block_scalar(content: str, indent: str = "    ") -> str:
    """YAML | block body: indent every line (including blanks)."""
    body = content.rstrip("\n") + "\n"
    return textwrap.indent(body, indent)


def _configmap(name: str, data: dict[str, str]) -> str:
    parts: list[str] = [
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        f"  name: {name}",
        "  annotations:",
        f"    vectis.grafana/generator: {GENERATOR_ANNOTATION}",
        "data:",
    ]

    for key in sorted(data):
        parts.append(f"  {key}: |")
        parts.append(_literal_block_scalar(data[key]))

    return "\n".join(parts)


def _load_inputs() -> tuple[str, dict[str, str]]:
    if not PROVIDER_SRC.is_file():
        raise FileNotFoundError(str(PROVIDER_SRC))
    provider = PROVIDER_SRC.read_text(encoding="utf-8")
    paths = _dashboard_json_paths()

    if not paths:
        raise ValueError(f"no *.json dashboards under {DASHBOARD_DIR}")

    dashboards = {p.name: p.read_text(encoding="utf-8") for p in paths}
    return provider, dashboards


def _banner() -> str:
    sources = [_rel_to_repo(PROVIDER_SRC)] + [_rel_to_repo(p) for p in _dashboard_json_paths()]
    return "\n".join(
        [
            f"# Generated by {GENERATOR_ANNOTATION} — DO NOT EDIT.",
            "# Sources: " + ", ".join(sources),
            "# Regenerate: make grafana-kube-configmaps",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        metavar="FILE",
        help="write output here instead of stdout",
    )
    args = parser.parse_args()

    try:
        provider, dashboards = _load_inputs()
    except FileNotFoundError as e:
        print(f"error: missing file {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    out = (
        _banner()
        + "\n---\n"
        + _configmap("vectis-grafana-dashboard-provider", {"dashboards.yaml": provider})
        + "\n---\n"
        + _configmap("vectis-grafana-dashboards", dashboards)
    )

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(out, encoding="utf-8")
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
