[api]
host = "localhost"
port = 8080
log_format = "text"

[queue]
port = 8081
metrics_port = 9081
register_with_registry = true
advertise_address = ""

[registry]
port = 8082

[log]
host = "localhost"

[log.grpc]
port = 8083
register_with_registry = true
advertise_address = ""

[log.sse]
port = 8084

[discovery]
registry_resolver_refresh = "10s"
registry_resolver_poll_timeout = "5s"
registry_resolver_error_refresh = "2s"
registry_registration_refresh = "45s"

[reconciler]
interval = "30s"

[database]
driver = "sqlite3"
dsn = "{{data_home}}/vectis/db.sqlite3"

[database.pgx_pool]
max_open_conns = 25
max_idle_conns = 10
conn_max_lifetime = "1h"
conn_max_idle_time = "15m"
