[api]
host = "localhost"
port = 8080

[queue]
port = 8081
register_with_registry = true
advertise_address = ""

[registry]
port = 8082

[log]
host = "localhost"

[log.grpc]
port = 8083
register_with_registry = true
advertise_address = ""

[log.sse]
port = 8084

[discovery]
registry_resolver_refresh = "10s"
registry_resolver_poll_timeout = "5s"
registry_resolver_error_refresh = "2s"
registry_registration_refresh = "45s"

[reconciler]
interval = "30s"

[database]
driver = "sqlite3"
dsn = "{{data_home}}/vectis/db.sqlite3"
