const sidebars = {
  docs: [
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/architecture',
        'concepts/glossary',
        'concepts/security',
        'concepts/internal-service-trust',
        'concepts/failure-domains',
        'concepts/compatibility',
      ],
    },
    {
      type: 'category',
      label: 'Using Vectis',
      items: [
        'using/your-first-job',
        'using/job-definition-reference',
        'using/artifacts',
        'using/cli-guide',
        'using/api-reference',
        'using/api-error-code-reference',
        'using/openapi-specification',
        'using/job-validation',
        'using/log-streaming',
        'using/idempotency-and-retries',
      ],
    },
    {
      type: 'category',
      label: 'Operating Vectis',
      items: [
        'operating/configuration',
        'operating/multi-cell',
        {
          type: 'category',
          label: 'Deployment',
          items: [
            'operating/deployment/production-topology-v1',
            'operating/deployment/production-linux',
            'operating/deployment/production-env-template',
            'operating/deployment/production-config-contract',
            'operating/deployment/production-security-checklist',
            'operating/deployment/reference-deployment-posture',
            'operating/deployment/trusted-proxy-client-ip',
            'operating/deployment/secrets-and-redaction',
            'operating/deployment/scaling-and-restarts',
          ],
        },
        {
          type: 'category',
          label: 'Reliability',
          items: [
            'operating/reliability/runbooks',
            'operating/reliability/production-monitoring',
            'operating/reliability/production-drills',
            'operating/reliability/repair-runbooks',
            'operating/reliability/dispatch-visibility',
            'operating/reliability/backup-restore',
            'operating/reliability/retention',
          ],
        },
        {
          type: 'category',
          label: 'Capacity',
          items: [
            'operating/capacity/capacity-load-envelope',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'operating/reference/run-state-reference',
            'operating/reference/configuration-key-reference',
            'operating/reference/authorization-reference',
            'operating/reference/audit-event-catalog',
            'operating/reference/database-schema',
            'operating/reference/metrics-catalog',
            'operating/reference/cli-operational-coverage',
            'operating/reference/health-check-catalog',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developing Vectis',
      items: [
        'developing/contexts',
        'developing/actions',
        'developing/worker-core-sdk',
        'developing/migrations',
        'developing/retry-policy',
        'developing/releases',
        'developing/production-readiness-evidence',
        {
          type: 'category',
          label: 'Performance',
          items: [
            'developing/performance/capacity-checks',
          ],
        },
        'developing/roadmap/planning',
        {
          type: 'category',
          label: 'Architecture Decisions',
          items: [
            'developing/architecture-decisions/index',
            'developing/architecture-decisions/async-enqueue-after-http-202',
            'developing/architecture-decisions/standalone-reconciler-process',
            'developing/architecture-decisions/database-claims-and-queue-deliveries',
            'developing/architecture-decisions/migration-compatibility-and-rollback',
            'developing/architecture-decisions/gossip-based-ha-registry',
            'developing/architecture-decisions/global-coordination-cell-local-execution',
            'developing/architecture-decisions/queue-pool-shards',
            'developing/architecture-decisions/api-edge-state-backend-contract',
            'developing/architecture-decisions/worker-execution-containment-providers',
            'developing/architecture-decisions/versioned-action-registry',
            'developing/architecture-decisions/artifact-service-local-cas',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
