package main

import (
	"github.com/spf13/cobra"
	"io"
	"net/http"
	"time"
	"vectis/internal/cli"
	"vectis/internal/config"
	"vectis/internal/retention"

	_ "vectis/internal/dbdrivers"
)

func newAPIRequest(method, path string, body io.Reader) (*http.Request, error) {
	req, err := http.NewRequest(method, config.PublicAPIBaseURL()+path, body)
	if err != nil {
		return nil, err
	}

	if token := effectiveToken(); token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	return req, nil
}

var apiHTTPClient = &http.Client{Timeout: 30 * time.Second}

func doAPIRequest(req *http.Request) (*http.Response, error) {
	return apiHTTPClient.Do(req)
}

func doAPIStreamRequest(req *http.Request) (*http.Response, error) {
	client := *apiHTTPClient
	client.Timeout = 0
	return client.Do(req)
}

const (
	cliGroupWorkflows  = "workflows"
	cliGroupAccess     = "access"
	cliGroupOperations = "operations"
)

func showCommandHelp(cmd *cobra.Command, args []string) {
	_ = cmd.Help()
}

var (
	podmanNetwork     string
	podmanKubeSpec    string
	podmanGrafanaSpec string
	podmanRenderOut   string
	resetYes          bool
	resetDryRun       bool
	retentionYes      bool
	retentionDryRun   bool
	retentionRunAge   time.Duration
	retentionDefAge   time.Duration
	retentionIdemAge  time.Duration
	retentionAuditAge time.Duration
	retentionLogDir   string
	runListJobID      string
	runListLimit      int
	runListCursor     int
	triggerIdemKey    string
	triggerCellIDs    []string
	runIdemKey        string
)

var rootCmd = &cobra.Command{
	Use:   "vectis-cli",
	Short: "Command line interface for Vectis",
	Long: `Vectis CLI provides a single entry point for jobs, runs, and user management.

Commands are grouped around the thing you want to work with:
  jobs       create, show, trigger, run, edit, and delete job definitions
  runs       show run status, list run history, cancel, fail, or retry runs
  cells      inspect execution cell routing and catalog state
  logs       stream run logs or follow future runs for a job
  auth       log in, log out, and manage API tokens`,
	Example: `  vectis-cli jobs create build.json
  vectis-cli jobs trigger build-main --follow
  vectis-cli jobs list --format json
  vectis-cli runs list build-main
  vectis-cli runs show run-123
  vectis-cli auth login
  vectis-cli health check --strict`,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		return validateOutputFormat(cliOutputFormat)
	},
}

func init() {
	cli.ConfigureVersion(rootCmd)
	rootCmd.PersistentFlags().StringVar(&cliOutputFormat, "format", outputText, "Output format: text or json")

	rootCmd.AddGroup(
		&cobra.Group{ID: cliGroupWorkflows, Title: "Workflows"},
		&cobra.Group{ID: cliGroupAccess, Title: "Access"},
		&cobra.Group{ID: cliGroupOperations, Title: "Operations"},
	)

	configureJobTriggerFlags(triggerCmd)
	configureJobRunFlags(runCmd)
	configureJobShowFlags(getCmd)
	configureJobCreateFlags(createCmd)
	configureJobDeleteFlags(deleteCmd)
	configureJobListFlags(listCmd)
	jobsCmd.AddCommand(listCmd, getCmd, createCmd, editCmd, deleteCmd, triggerCmd, runCmd)
	rootCmd.AddCommand(jobsCmd)

	configureRunListFlags(runListCmd)
	configureForceFailFlags(forceFailCmd)
	configureRepairMarkFlags(repairMarkSucceededCmd)
	configureRepairMarkFlags(repairMarkFailedCmd)
	configureRepairMarkFlags(repairMarkCancelledCmd)
	configureRepairMarkFlags(repairMarkAbandonedCmd)
	runRepairCmd.AddCommand(repairMarkSucceededCmd, repairMarkFailedCmd, repairMarkCancelledCmd, repairMarkAbandonedCmd, repairMarkQueuedCmd)
	runsCmd.AddCommand(runListCmd, runGetCmd, runCancelCmd, runRepairCmd, forceFailCmd, forceRequeueCmd)
	rootCmd.AddCommand(runsCmd)

	cellsCmd.AddCommand(cellsStatusCmd)
	rootCmd.AddCommand(cellsCmd)

	configureLogFilterFlags(logsRunCmd)
	configureLogFilterFlags(logsJobCmd)
	configureLogsJobFlags(logsJobCmd)
	logsCmd.AddCommand(logsRunCmd, logsJobCmd)
	rootCmd.AddCommand(logsCmd)

	configureLoginFlags(loginCmd)
	authCmd.AddCommand(loginCmd, logoutCmd)
	tokenCmd.AddCommand(tokenListCmd)
	configureTokenCreateFlags(tokenCreateCmd)
	tokenCmd.AddCommand(tokenCreateCmd, tokenDeleteCmd)
	authCmd.AddCommand(tokenCmd)
	rootCmd.AddCommand(authCmd)

	namespaceCreateCmd.Flags().Int64("parent-id", 0, "Parent namespace ID (default: root)")
	namespaceCmd.GroupID = cliGroupAccess
	namespaceCmd.Run = showCommandHelp
	namespaceCmd.AddCommand(namespaceListCmd, namespaceGetCmd, namespaceCreateCmd, namespaceDeleteCmd)
	rootCmd.AddCommand(namespaceCmd)

	userCreateCmd.Flags().String("password", "", "Initial password (default: generated by API)")
	userChangePasswordCmd.Flags().Int64("user-id", 0, "Target user ID (default: current user)")
	userChangePasswordCmd.Flags().String("current-password", "", "Current password for self-service password changes")
	userChangePasswordCmd.Flags().String("new-password", "", "New password")
	userCmd.GroupID = cliGroupAccess
	userCmd.Run = showCommandHelp
	userCmd.AddCommand(userListCmd, userGetCmd, userCreateCmd, userEnableCmd, userDisableCmd, userDeleteCmd, userChangePasswordCmd)
	rootCmd.AddCommand(userCmd)

	roleBindingCmd.GroupID = cliGroupAccess
	roleBindingCmd.Run = showCommandHelp
	roleBindingCmd.AddCommand(roleBindingListCmd, roleBindingCreateCmd, roleBindingDeleteCmd)
	rootCmd.AddCommand(roleBindingCmd)

	configureDoctorFlags(doctorCmd)
	healthCmd.AddCommand(doctorCmd)
	rootCmd.AddCommand(healthCmd)

	databaseCmd.AddCommand(migrateCmd)
	rootCmd.AddCommand(databaseCmd)

	deployPodmanCmd.PersistentFlags().StringVar(&podmanNetwork, "network", "pasta", "Podman network mode for play kube")
	deployPodmanCmd.PersistentFlags().StringVar(&podmanKubeSpec, "kube-spec", defaultPodmanKubeSpec, "Path to the Podman kube spec template")
	deployPodmanCmd.PersistentFlags().StringVar(&podmanGrafanaSpec, "grafana-spec", defaultPodmanGrafanaSpec, "Path to generated Grafana ConfigMaps")
	deployPodmanInitCmd.Flags().Bool("rotate", false, "Regenerate deployment secrets")
	deployPodmanRenderCmd.Flags().Bool("rotate", false, "Regenerate deployment secrets before rendering")
	deployPodmanRenderCmd.Flags().StringVarP(&podmanRenderOut, "output", "o", "-", "Rendered manifest output path, or '-' for stdout")
	deployPodmanCmd.AddCommand(deployPodmanInitCmd)
	deployPodmanCmd.AddCommand(deployPodmanRenderCmd)
	deployPodmanCmd.AddCommand(deployPodmanUpCmd)
	deployPodmanCmd.AddCommand(deployPodmanDownCmd)
	deployPodmanCmd.AddCommand(deployPodmanStatusCmd)
	deployCmd.AddCommand(deployPodmanCmd)
	rootCmd.AddCommand(deployCmd)

	configureResetFlags(resetCmd)
	localCmd.AddCommand(resetCmd)
	rootCmd.AddCommand(localCmd)

	defaultRetention := retention.DefaultPolicy()
	retentionCleanupCmd.Flags().BoolVar(&retentionYes, "yes", false, "Confirm deletion of retention-eligible records")
	retentionCleanupCmd.Flags().BoolVar(&retentionDryRun, "dry-run", false, "Print the records that would be deleted")
	retentionCleanupCmd.Flags().DurationVar(&retentionRunAge, "terminal-run-age", defaultRetention.TerminalRuns, "Delete terminal runs older than this duration (0 disables)")
	retentionCleanupCmd.Flags().DurationVar(&retentionDefAge, "job-definition-age", defaultRetention.JobDefinitions, "Delete unreferenced ephemeral job definitions older than this duration (0 disables)")
	retentionCleanupCmd.Flags().DurationVar(&retentionIdemAge, "idempotency-age", defaultRetention.IdempotencyKeys, "Delete idempotency keys older than this duration (0 disables)")
	retentionCleanupCmd.Flags().DurationVar(&retentionAuditAge, "audit-age", defaultRetention.AuditLog, "Delete audit log rows older than this duration (0 disables)")
	retentionCleanupCmd.Flags().StringVar(&retentionLogDir, "log-storage-dir", "", "Optional durable run log directory to prune for deleted terminal runs")
	retentionCmd.AddCommand(retentionCleanupCmd)
	rootCmd.AddCommand(retentionCmd)
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		runCLIError(err)
	}
}
